# Generated by Django 3.2.6 on 2021-08-31 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20210831_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='categories',
        ),
    ]
