# Generated by Django 3.2.6 on 2021-08-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_alter_budget_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='categories',
            field=models.ManyToManyField(to='money.Category'),
        ),
    ]
