# Generated by Django 3.2.6 on 2021-09-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_budget_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name_plural': 'Card Name'},
        ),
    ]
