# Generated by Django 3.2.6 on 2021-09-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0010_alter_card_cardname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardName',
            field=models.CharField(max_length=20, unique=True, verbose_name='Card Name/Bank Account'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
